### PR TITLE
code modularization

### PR DESCRIPTION
**Pull request by chendiblessing**
a documentation on code modularization

### CODE REVIEW

**Review by stephane-segning — CHANGES_REQUESTED** [review]
Good work @chendiblessing! Now, convert this file into a `.md` file and add some code example to it. For example, what will happen to this code:

```python
# file.py
def function1(args1):
    # Some implementation that uses `function2`
    pass

def function2(args2):
    # Some unknown implementation
    pass

if __name__ == '__main__':
    function1("someArgument")
```

**Comment by chendiblessing** [comment]
Sir @stephane-segning required changes have been made on the file

**Comment by stephane-segning** [comment]
@chendiblessing how can I modularize this code:
```python
# file.py
def function1(args1):
    # Some implementation that uses `function2`
    pass

def function2(args2):
    # Some unknown implementation
    pass

if __name__ == '__main__':
    function1("someArgument")
```

**Review by stephane-segning — APPROVED** [review]

**Comment by chendiblessing** [comment]
> @chendiblessing how can I modularize this code:
> 
> ```python
> # file.py
> def function1(args1):
>     # Some implementation that uses `function2`
>     pass
> 
> def function2(args2):
>     # Some unknown implementation
>     pass
> 
> if __name__ == '__main__':
>     function1("someArgument")
> ```

sir the would have to put the script in separate modules where u have function 2 in one module then in the other module you import function 1 and use it

**Pull request merged**
