### PR TITLE
implementation of user friendly error message

### PR DESCRIPTION
**Pull request by Blindspot22**
@stephane-segning I implemented user friendly error message, such that when a wrong URL is used in the input interface a pop up message is seen directing the user on how to go about

### CODE REVIEW

**Review by Awambeng — APPROVED** [review]
good job for the moment!

**Comment by stephane-segning** [comment]
Good job guys!

**Comment by stephane-segning** [comment]
Yes Scott

**Comment by Blindspot22** [comment]
🫡

**Pull request merged**
