### PR TITLE
feature(global) adding scraping parameters

### PR DESCRIPTION
**Pull request by AssahBismarkabah**
Implementing functionality for customizing scraping parameters, such as the depth of scraping or specific data to extract.

Allow users to set preferences for scraping options through the user interface

### CODE REVIEW

**Review by stephane-segning — COMMENTED** [review]
This need to be tested manually again. Please, @sinke237

**Comment by AssahBismarkabah** [comment]
Hello @stephane-segning @sinke237 here is the display of the input parameters by the user with the required depth of scraping and specific data to extract.
Screenshot from 2023-11-20 12-19-08

which needs integrated with the scraping functionality of user story 3:implement data scraping function 
and the corresponding route in the app.py `@app.route('/scrape', methods=['POST'])` to be saved in the CSV file

**Comment by stephane-segning** [comment]
Please link a Ticket to this one

**Comment by AssahBismarkabah** [comment]
hello sir @stephane-segning  please how do i do that sir?

**Review by stephane-segning — APPROVED** [review]

**Pull request merged**
