### PR TITLE
Added savedata.py

### PR DESCRIPTION
**Pull request by Elwizzy12**
@Elwizzy12 and @chendiblessing worked on a feature to implement a data saving function
@stephane-segning Please review

### CODE REVIEW

**Review by stephane-segning — APPROVED** [review]
Perfect!

**Comment by stephane-segning** [comment]
Don't forget to associate it with a ticket

**Comment by stephane-segning** [comment]
Next time, change the name too 🥅

**Comment by Elwizzy12** [comment]
> Don't forget to associate it with a ticket

okay sir, Noted!

**Pull request merged**
