### PR TITLE
Implement the frontend for fetching results

### PR DESCRIPTION
**Pull request by bryandino673**

### CODE REVIEW

**Comment by bryandino673** [comment]
@stephane-segning Here is the adjusted code sir

**Comment by bryandino673** [comment]
Done by @Elwizzy12  and @bryandino673

**Comment by stephane-segning** [comment]
@bryandino673 Can you add some screenshot of the working app here?

**Comment by bryandino673** [comment]
@stephane-segning  sir the screenshot of the codes output has been added

**Comment by stephane-segning** [comment]
@bryandino673 I was saying here as a comment, not in the code.

**Review by stephane-segning — APPROVED** [review]
Haha, @bryandino673 I'll need you to explain it to me next time 😊

**Pull request merged**
